### ISSUE TITLE
Create a new release tag

### ISSUE THREAD

**Issue by Etn40ff** [Blub/netevent#23] opened 2021-11-16 19:38 UTC
While packaging `netevent` for `toltec` I was requested for a release tag. Could you please make one that incorporates recent changes? Thanks

**Comment by Eeems** [comment] 2021-11-29 23:49
Duplicate of #17?

**Comment by Blub** [comment] 2021-11-30 19:35
Sort of. I'll try to find some time soon. Lately I'm not that often around multiple devices to do proper testing with as my setups have changed a lot.

**Closed** 2021-12-03 18:45 UTC

**Comment by Etn40ff** [comment] 2021-12-03 19:57
Tanks
